# service for the application 
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:  # Corrected spelling here
    app: go-web-app
spec:
  ports:
    - port: 80
      targetPort: 8080  # Corrected to `targetPort`
      protocol: TCP
  selector:
    app: go-web-app  # Move selector outside of ports
  type: ClusterIP

